# Generated by Django 4.0 on 2022-11-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommender',
            name='K',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='N',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='P',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='humidity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='ph',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='rainfall',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='croprecommender',
            name='temperature',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='humidity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='moisture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='nitrogen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='phosphorus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='potassium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommender',
            name='temperature',
            field=models.CharField(max_length=100),
        ),
    ]
